---
name: SlapperPlayerCount
version: 3.1.0
main: ethaniccc\SlapperPlayerCount\Main
description: Get the amount of players on a world or server using Slapper!
api: 5.0.0
depend:
  - Slapper
...
